# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-c7c866b936274076ad052c5a83684f9e
      model-name: deepseek-chat
      # 优化结构化输出的稳定性
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
      log-requests: true
      log-responses: true


