# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-c7c866b936274076ad052c5a83684f9e
      model-name: deepseek-chat
      # 优化结构化输出的稳定性
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
      log-requests: true
      log-responses: true
      # 流式大模型
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-c7c866b936274076ad052c5a83684f9e
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: ${COS_HOST:ai-code-mother-1365374837.cos.ap-guangzhou.myqcloud.com}
    secretId: ${COS_SECRET_ID:your-secret-id-here}
    secretKey: ${COS_SECRET_KEY:your-secret-key-here}
    region: ${COS_REGION:ap-guangzhou}
    bucket: ${COS_BUCKET:ai-code-mother-1365374837}




